### ISSUE TITLE
KeyError on Request for Django REST 3.11

### ISSUE THREAD

**Issue by kron-spar** [praekelt/django-ultracache#8]
I just stumbled across this project and it looks like a great fit for something I am working on. After reading through the documentation, I tried to implement this in my project at a very simple level. Unfortunately after following the installation instructions, I received a few errors. 

I my settings.py I included `ultracache` in the installed apps. 

I also included this Ultra Cache settings in the settings.py as well.
```json
ULTRACACHE = {
    "drf": {"viewsets": {"*": {}}}

}
```

I made sure that `django.template.context_processors.request` was present in the context_settings as well.

Upon making a GET request to a viewset, I get a 500 internal server error and the following output. 

```bash
Traceback (most recent call last):
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/kron/workspace/Food-Groupings/FoodPairings/Food/api.py", line 186, in list
    return Response(serializer.data)
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/rest_framework/serializers.py", line 760, in data
    ret = super().data
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/ultracache/monkey.py", line 195, in wrapped
    request = context.context["request"]
KeyError: 'request'
```
After seeing that error, I tried to explicitly add the `@ultracache()` decorator to my viewset. I got a different error after that as well.

```bash
 File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kron/workspace/Food-Groupings/FoodPairings/api/urls.py", line 3, in <module>
    from Food.api import LinkViewSet, FoodViewSet
  File "/home/kron/workspace/Food-Groupings/FoodPairings/Food/api.py", line 16, in <module>
    from ultracache.decorators import cached_get, ultracache
  File "/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/ultracache/decorators.py", line 9, in <module>
    from django.utils.decorators import available_attrs
ImportError: cannot import name 'available_attrs' from 'django.utils.decorators' (/home/kron/workspace/Food-Groupings/env/lib/python3.7/site-packages/django/utils/decorators.py)
```

Any help would be appreciated!

**Comment by hedleyroos** [comment]
Hi there. Which version of Django are you using?

**Comment by hedleyroos** [comment]
The project has moved to https://github.com/hedleyroos/django-ultracache. I have created a test for Django 3 and DRF 3.11 and it is passing. Would you mind testing the latest code please?
